
// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI agent for generating rich, descriptive content about festivals.
 * This flow's ONLY responsibility is to provide text. It does not perform any calculations.
 *
 * - festivalDescriberFlow - A function that generates descriptive text.
 * - FestivalDescriberInput - The input type for the flow.
 * - FestivalDescriberOutput - The return type for the flow.
 */

import { ai } from '@/ai/genkit';
import { z } from 'zod';

const FestivalDescriberInputSchema = z.object({
    festivalName: z.string().describe("The official name of the festival, e.g., 'Krishna Janmashtami'."),
    day: z.string().describe("The day of the week the festival falls on, e.g., 'Monday'."),
});

const FestivalDescriberOutputSchema = z.object({
  mainDescription: z.string().describe("A brief, beginner-friendly explanation of the festival's overall significance and history."),
  summary: z.string().describe("A detailed summary for the user, highlighting the key aspects of the festival day."),
  rituals: z.string().describe("A summary of the main rituals and customs followed during the festival."),
  calculationMethod: z.string().describe("A step-by-step explanation of how the festival's main date is determined using traditional astrological principles. This should be a numbered list in a single string, with each step separated by a newline character (\\n)."),
});

export type FestivalDescriberOutput = z.infer<typeof FestivalDescriberOutputSchema>;

export const festivalDescriberFlow = ai.defineFlow(
  {
    name: 'festivalDescriberFlow',
    inputSchema: FestivalDescriberInputSchema,
    outputSchema: FestivalDescriberOutputSchema,
  },
  async (input) => {
    const prompt = `You are a master Vedic astrologer (Jyotishi). Your task is to provide rich, descriptive information for a Hindu festival. You will be given the name of the festival and the day it falls on. You must generate all the textual content.

    **Festival Name:** "${input.festivalName}"
    **Day of Week:** ${input.day}

    **Your Task:**
    Based on your knowledge of this festival, generate the following content. **DO NOT perform any date or time calculations.**

    1.  **mainDescription**: An overall summary of the festival's significance.
    2.  **summary**: A detailed summary for the user, highlighting what is important about this festival day.
    3.  **rituals**: Describe the primary rituals for the day.
    4.  **calculationMethod**: Explain how this festival's primary date is determined based on the Tithi and Paksha. Format as a numbered list separated by newlines (\\n).
    
    Compile all this information into the required JSON format.
    `;

    const { output } = await ai.generate({
      model: 'googleai/gemini-2.5-flash',
      prompt: prompt,
      output: {
        schema: FestivalDescriberOutputSchema,
      },
    });

    if (!output) {
      throw new Error(`The descriptive content for '${input.festivalName}' could not be generated.`);
    }
    
    return output;
  }
);
