
// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A reliable system for getting festival details.
 * This file is now the central point for combining trusted local data
 * with live Panchang data to generate accurate festival information.
 *
 * - festivalDetails - A new function that orchestrates the data gathering.
 */
import { panchangGenerator } from './panchang-generator';
import { festivalDescriberFlow } from './festival-describer';
import { festivalDatabase } from '@/lib/festival-data';
import type { FestivalDetails } from '@/lib/types';
import { format, parse } from 'date-fns';

export async function festivalDetails(query: string): Promise<FestivalDetails> {
    const normalizedQuery = query.toLowerCase().trim();

    // 1. Find the festival date from our reliable local database
    const festivalInfo = festivalDatabase.find(f => normalizedQuery.includes(f.name.toLowerCase()));

    if (!festivalInfo) {
        throw new Error(`The festival "${query}" was not found in our database. Please try a different name or check back later.`);
    }
    
    const festivalDate = festivalInfo.date;

    // 2. Fetch accurate panchang data for that specific date from Prokerala
    // The panchang object now contains accurate tithi.start and tithi.end times.
    const panchang = await panchangGenerator({ date: festivalDate });

    // 3. Fetch descriptive content from a dedicated, simple AI flow (no time generation)
    const descriptionData = await festivalDescriberFlow({ festivalName: festivalInfo.name, day: panchang.day });

    // 4. Construct the final, accurate result
    const finalResult: FestivalDetails = {
        festivalName: `${festivalInfo.name} ${format(parse(festivalDate, 'yyyy-MM-dd', new Date()), 'yyyy')}`,
        mainDescription: descriptionData.mainDescription,
        calculationMethod: descriptionData.calculationMethod,
        dailyDetails: [{
            dayName: festivalInfo.name,
            summary: descriptionData.summary,
            rituals: descriptionData.rituals,
            // All panchang data comes directly from the reliable panchangGenerator
            date: festivalDate,
            day: panchang.day,
            tithi: panchang.tithi,
            nakshatra: panchang.nakshatra,
            rahuKaal: panchang.rahuKaal,
            gulikaKaal: panchang.gulikaKaal,
            yamaganda: panchang.yamaganda,
            abhijitMuhurat: panchang.abhijitMuhurat,
            // **FIX**: These timings now come directly from the Prokerala response via the panchangGenerator
            tithiBegins: panchang.tithiStartTime,
            tithiEnds: panchang.tithiEndTime,
        }]
    };
    
    return finalResult;
}
