// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI agent for finding festival details.
 * This agent now uses a hybrid approach:
 * 1. AI determines the start/end dates and provides rich descriptions.
 * 2. It then fetches precise daily panchang data from the Prokerala-powered
 *    panchangGenerator for each day of the festival to ensure accuracy.
 *
 * - festivalFinder - A function that handles the festival finding process.
 * - FestivalFinderInput - The input type for the festivalFinder function.
 * - FestivalDetails - The return type for the festivalFinder function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import { FestivalFinderInputSchema, FestivalFinderOutputSchema } from '@/lib/types';
import type { FestivalFinderInput, FestivalDetails } from '@/lib/types';
import { connectToDatabase } from '@/lib/mongodb';
import { panchangGenerator } from './panchang-generator';
import { eachDayOfInterval, parse, format } from 'date-fns';

export async function festivalFinder(input: FestivalFinderInput): Promise<FestivalDetails> {
  const { db } = await connectToDatabase();
  const cacheKey = `festival_v2_${input.query.toLowerCase().trim()}`;
  const cacheCollection = db.collection('festival_cache');

  // 1. Check for a valid cache entry in MongoDB
  const cachedData = await cacheCollection.findOne({ _id: cacheKey });
  if (cachedData) {
    const { _id, ...festivalData } = cachedData;
    return festivalData as FestivalDetails;
  }
  
  // 2. If not in cache, call the AI flow to get date range and descriptions
  const aiResult = await festivalFinderFlow(input);

  // 3. For each day in the date range, fetch accurate panchang data
  const startDate = parse(aiResult.startDate, 'yyyy-MM-dd', new Date());
  const endDate = parse(aiResult.endDate, 'yyyy-MM-dd', new Date());
  const festivalDays = eachDayOfInterval({ start: startDate, end: endDate });

  const dailyDetails = await Promise.all(
      festivalDays.map(async (day, index) => {
          const dateString = format(day, 'yyyy-MM-dd');
          const panchang = await panchangGenerator({ date: dateString });
          const aiDayDetail = aiResult.dailyDetails[index] || aiResult.dailyDetails[0];

          return {
              dayName: aiDayDetail.dayName,
              date: dateString,
              day: panchang.day,
              summary: aiDayDetail.summary.replace('YYYY-MM-DD', dateString), // Ensure date is correct
              tithi: panchang.tithi,
              nakshatra: panchang.nakshatra,
              // Use AI for tithi timings as panchang doesn't provide it
              tithiBegins: aiDayDetail.tithiBegins,
              tithiEnds: aiDayDetail.tithiEnds, 
              rituals: aiDayDetail.rituals,
              rahuKaal: panchang.rahuKaal,
              gulikaKaal: panchang.gulikaKaal,
              yamaganda: panchang.yamaganda,
              abhijitMuhurat: panchang.abhijitMuhurat,
          };
      })
  );

  const finalResult: FestivalDetails = {
      festivalName: aiResult.festivalName,
      mainDescription: aiResult.mainDescription,
      calculationMethod: aiResult.calculationMethod,
      dailyDetails: dailyDetails,
  };


  // 4. Store the new, combined result in the MongoDB cache
  await cacheCollection.updateOne(
    { _id: cacheKey },
    { $set: finalResult },
    { upsert: true }
  );
  
  return finalResult;
}

// This schema is for the AI's intermediate output
const FestivalAiOutputSchema = FestivalFinderOutputSchema.extend({
    startDate: z.string().describe("The start date of the festival in YYYY-MM-DD format."),
    endDate: z.string().describe("The end date of the festival in YYYY-MM-DD format. For single day festivals, this will be the same as the start date."),
});


const festivalFinderFlow = ai.defineFlow(
  {
    name: 'festivalFinderFlow',
    inputSchema: FestivalFinderInputSchema,
    outputSchema: FestivalAiOutputSchema,
  },
  async (input) => {
    
    const prompt = `You are a master Vedic astrologer (Jyotishi). Your task is to provide descriptive information and key dates for a Hindu festival based on a user's query. You MUST NOT provide detailed panchang timings (like Rahu Kaal, etc.) as that will be fetched from a precise API later.

    User query: "${input.query}"
    
    **Instructions:**

    **Step 1: Determine Festival Dates**
    - Based on the user's query, determine the exact START DATE and END DATE of the festival for the specified year.
    - If no year is specified, assume the current or next upcoming instance.
    - You MUST output these dates in the 'startDate' and 'endDate' fields in YYYY-MM-DD format.
    
    **Step 2: Generate Descriptive Content**
    - **festivalName**: The official name of the festival, including the year (e.g., "Durga Puja 2025").
    - **mainDescription**: An overall summary of the festival's significance.
    - **dailyDetails**: Generate an entry for EACH significant day of the festival.
        - For each day, provide the 'dayName' (e.g., "Maha Ashtami") and a 'summary' of its importance.
        - **Crucially**, in the summary for each day, use 'YYYY-MM-DD' as a placeholder for the date. The final system will insert the correct date.
        - Describe the primary 'rituals' for that day.
        - Provide the 'tithi' name and approximate 'tithiBegins' and 'tithiEnds' times in 'YYYY-MM-DD HH:mm' format (using placeholder date).
        - **DO NOT** include Nakshatra, Rahu Kaal, Gulika Kaal, or other detailed panchang elements. They will be replaced by an accurate API call.

    **Step 3: Explain Calculation Method**
    - In the 'calculationMethod' field, explain how you determined the festival's primary date or start date. Focus on the core astrological rule (e.g., the Tithi and Paksha). Format as a numbered list separated by newlines (\\n).
    
    Compile all this information into the required JSON format.
    `;

    const {output} = await ai.generate({
        model: 'googleai/gemini-2.5-flash',
        prompt: prompt,
        output: {
            schema: FestivalAiOutputSchema,
        },
    });

    if (!output) {
      throw new Error(`The festival details for '${input.query}' could not be generated. Please check the spelling or try a different year.`);
    }
    
    return output;
  }
);
