// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A Kundli Matching (Gun Milan) AI agent that uses pre-computed data
 * and now caches results in MongoDB for improved performance.
 *
 * - kundliMatching - A function that handles the Kundli matching process.
 * - KundliMatchingInput - The input type for the kundliMatching function.
 * - KundliMatchingResult - The return type for the kundliMatching function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';
import { lookupPlanetaryData } from '@/lib/astrology-lookup';
import { connectToDatabase } from '@/lib/mongodb';

const BirthDetailsSchema = z.object({
  name: z.string().describe("The person's name."),
  dateOfBirth: z.string().describe("The person's date of birth in YYYY-MM-DD format."),
  timeOfBirth: z.string().describe("The person's time of birth in HH:MM format."),
  placeOfBirth: z.string().describe("The person's place of birth (e.g., city, country)."),
});

const KundliMatchingInputSchema = z.object({
  boyDetails: BirthDetailsSchema,
  girlDetails: BirthDetailsSchema,
});
export type KundliMatchingInput = z.infer<typeof KundliMatchingInputSchema>;

// This internal schema is used to pass precise data to the AI.
const InternalMatchingDataSchema = z.object({
  boy: z.object({
    name: z.string(),
    rashi: z.string(),
    nakshatra: z.string(),
    nakshatraPada: z.number(),
    marsHouse: z.number().describe("The house position of Mars, needed for Manglik check."),
  }),
  girl: z.object({
    name: z.string(),
    rashi: z.string(),
    nakshatra: z.string(),
    nakshatraPada: z.number(),
    marsHouse: z.number().describe("The house position of Mars, needed for Manglik check."),
  }),
});


const DoshaResultSchema = z.object({
  hasDosha: z.boolean().describe("Whether the person has the dosha."),
  description: z.string().describe("A brief description of the dosha's potential impact, based on the astrological rules. State 'No significant dosha found' if hasDosha is false."),
});

const KootaDetailSchema = z.object({
  name: z.string().describe("The name of the Koota (e.g., 'Varna Koota')."),
  boyAttribute: z.string().describe("The boy's attribute for this Koota (e.g., 'Brahmin'), derived from his Rashi."),
  girlAttribute: z.string().describe("The girl's attribute for this Koota (e.g., 'Kshatriya'), derived from her Rashi."),
  pointsAwarded: z.number().describe("The points awarded for this Koota based on the matching rules."),
  maxPoints: z.number().describe("The maximum possible points for this Koota."),
  description: z.string().describe("A brief explanation of the matching result for this Koota."),
});

const AdvancedCompatibilitySchema = z.object({
  lagna: z.string().describe("A detailed analysis of the Lagna-Lagna (Ascendant) compatibility, focusing on core personality and life path alignment based on the relationship between the two ascendant signs."),
  moonSign: z.string().describe("An analysis of the Moon sign compatibility, detailing emotional connection, understanding, and domestic harmony based on the relationship between the two Moon signs."),
  venusMars: z.string().describe("An analysis of the Venus-Mars synergy, focusing on love, affection, attraction, and romantic chemistry based on their placements in both charts."),
  mental: z.string().describe("An analysis of the mental temperament compatibility based on the Moon-Mercury relationship in both charts, covering communication styles and intellectual connection."),
});

const SpiritualCompatibilityIndexSchema = z.object({
  score: z.number().min(0).max(100).describe("The AI-calculated Spiritual Compatibility Index (SCI) score from 0 to 100, based on a holistic analysis of all factors."),
  summary: z.string().describe("A summary explaining what the SCI score represents for the couple's spiritual and long-term harmony."),
  marriageSuccessPrediction: z.string().describe("An engaging, fun, but insightful prediction about the potential success and nature of the marriage, based on the overall analysis."),
});


const KundliMatchingResultSchema = z.object({
  score: z.number().describe('The compatibility score out of 36 based on the Ashtakoot Milan system.'),
  ashtakootDetails: z.array(KootaDetailSchema).length(8).describe("An array containing the results for each of the 8 Kootas of the Ashtakoot Milan system."),
  summary: z.string().describe('A detailed analysis of the compatibility, explaining the score and key matching points in simple language.'),
  remedy: z.string().optional().describe('A suggested remedy if the compatibility score is low or if there are significant doshas.'),
  boyManglik: DoshaResultSchema.describe("The Manglik Dosha analysis for the boy, based on Mars's placement."),
  girlManglik: DoshaResultSchema.describe("The Manglik Dosha analysis for the girl, based on Mars's placement."),
  nadiDosha: DoshaResultSchema.describe("The Nadi Dosha analysis for the match, based on the Nadi Koota calculation."),
  advancedCompatibility: AdvancedCompatibilitySchema.describe("The advanced compatibility analysis beyond the Guna Milan system."),
  spiritualCompatibilityIndex: SpiritualCompatibilityIndexSchema.describe("The unique, AI-generated Spiritual Compatibility Index."),
});
export type KundliMatchingResult = z.infer<typeof KundliMatchingResultSchema>;

export async function kundliMatching(input: KundliMatchingInput): Promise<KundliMatchingResult> {
    const { db } = await connectToDatabase();
    const cacheKey = JSON.stringify(input);
    const cacheCollection = db.collection('kundli_matching_cache');

    // 1. Check for a valid cache entry in MongoDB
    const cachedData = await cacheCollection.findOne({ _id: cacheKey });
    if (cachedData) {
        const { _id, ...matchingData } = cachedData;
        return matchingData as KundliMatchingResult;
    }

    // Step 2: Look up pre-computed planetary data for boy and girl.
    const boyData = lookupPlanetaryData(input.boyDetails.dateOfBirth);
    const girlData = lookupPlanetaryData(input.girlDetails.dateOfBirth);

    if (!boyData || !girlData) {
        throw new Error("Could not find planetary data for the given dates. Please ensure the date is within the supported range.");
    }

    // Step 3: Prepare the precise data for the AI.
    const internalInput = {
        boy: {
            name: input.boyDetails.name,
            rashi: boyData.Moon.rashi,
            nakshatra: boyData.Moon.nakshatra,
            nakshatraPada: boyData.Moon.nakshatraPada,
            marsHouse: 7, // Simulated lookup
        },
        girl: {
            name: input.girlDetails.name,
            rashi: girlData.Moon.rashi,
            nakshatra: girlData.Moon.nakshatra,
            nakshatraPada: girlData.Moon.nakshatraPada,
            marsHouse: 2, // Simulated lookup
        },
    };

    // Step 4: Call the AI flow with the precise data.
    const result = await kundliMatchingFlow(internalInput);

    // Step 5: Store the new result in the MongoDB cache
    await cacheCollection.updateOne(
        { _id: cacheKey },
        { $set: result },
        { upsert: true }
    );

    return result;
}

const prompt = ai.definePrompt({
  name: 'kundliMatchingRuleBasedPrompt',
  input: {schema: InternalMatchingDataSchema },
  output: {schema: KundliMatchingResultSchema},
  prompt: `You are a master Vedic astrologer with deep expertise in marriage compatibility. Your task is to conduct a thorough compatibility analysis based ONLY on the precise astrological data provided below. Do NOT calculate anything yourself; apply the rules of Ashtakoot Milan to the given data.

  Boy's Data:
  - Name: {{{boy.name}}}
  - Rashi (Moon Sign): {{{boy.rashi}}}
  - Nakshatra: {{{boy.nakshatra}}} (Pada {{{boy.nakshatraPada}}})
  - Mars is in house: {{{boy.marsHouse}}}

  Girl's Data:
  - Name: {{{girl.name}}}
  - Rashi (Moon Sign): {{{girl.rashi}}}
  - Nakshatra: {{{girl.nakshatra}}} (Pada {{{girl.nakshatraPada}}})
  - Mars is in house: {{{girl.marsHouse}}}

  You MUST perform a three-level analysis based ONLY on this provided data:

  **Level 1: Foundational Analysis (Ashtakoot Milan)**
  1.  **Ashtakoot Milan Detailed Breakdown**: Provide a detailed breakdown for EACH of the 8 Kootas by applying the matching rules to their given Nakshatras and Rashis. The 8 Kootas are: Varna (1 pt), Vasya (2 pts), Tara/Dina (3 pts), Yoni (4 pts), Graha Maitri (5 pts), Gana (6 pts), Rashi/Bhakoot (7 pts), and Nadi (8 pts). For each Koota, you must derive the boy's and girl's attributes from the provided data, then provide the points awarded, the maximum points, and a brief description of the match.
  2.  **Calculate Final Score**: The final score MUST be the sum of the points from the 8 Kootas.
  3.  **Dosha Analysis**:
      -   **Manglik Dosha**: Analyze each person for Mars's placement in houses 1, 4, 7, 8, or 12 from their given Mars house position.
      -   **Nadi Dosha**: Determine if the couple has Nadi Dosha based on their Nakshatras. This result must be consistent with the Nadi Koota calculation.
  4.  **Write Summary & Remedy**: Based on the score and doshas, write a comprehensive summary. If the score is below 18 OR if a major dosha exists, suggest a relevant remedy.

  **Level 2: Advanced Compatibility Insights (Beyond Gunas)**
  Provide deeper analysis based on the given Rashis:
  1.  **Lagna-Lagna Compatibility**: Assume Lagna is the same as Rashi for this analysis. Analyze core personality alignment.
  2.  **Moon Sign Compatibility**: Analyze emotional connection based on their given Moon signs.
  3.  **Venus-Mars Synergy**: Provide a generic analysis of the importance of Venus-Mars synergy in a match.
  4.  **Mental Temperament (Moon-Mercury)**: Provide a generic analysis of the importance of Moon-Mercury connections.

  **Level 3: Spiritual Compatibility Index (SCI)**
  This is your unique, AI-powered score based on a holistic view of all factors.
  1.  **Calculate SCI Score**: A holistic score from 0-100.
  2.  **SCI Summary**: Explain what this score means for the couple.
  3.  **Marriage Success Prediction**: Provide a fun, insightful prediction.

  Generate a complete response in the specified JSON format, ensuring all fields are populated with insightful, well-written analysis derived from the rules applied to the given data.`,
});

const kundliMatchingFlow = ai.defineFlow(
  {
    name: 'kundliMatchingFlow',
    inputSchema: InternalMatchingDataSchema,
    outputSchema: KundliMatchingResultSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
