
// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A Kundli generator AI agent.
 * This flow now uses a hybrid approach: local calculations for core chart data,
 * AI for descriptive interpretations, and MongoDB for persistent caching.
 *
 * - kundliGenerator - A function that handles the Kundli generation process.
 * - KundliGeneratorInput - The input type for the kundliGenerator function.
 * - KundliGeneratorOutput - The return type for the kundliGenerator function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import { lookupPlanetaryData } from '@/lib/astrology-lookup';
import { getTithi, getNakshatra, getYoga, getKarana, getVara } from '@/lib/astrology-calculator';
import { connectToDatabase } from '@/lib/mongodb';


const KundliGeneratorInputSchema = z.object({
  name: z.string().describe("The user's name."),
  dateOfBirth: z.string().describe("The user's date of birth in YYYY-MM-DD format."),
  timeOfBirth: z.string().describe("The user's time of birth in HH:MM format."),
  placeOfBirth: z.string().describe("The user's place of birth (e.g., city, country). This should ideally be lat,lon for accuracy."),
});
export type KundliGeneratorInput = z.infer<typeof KundliGeneratorInputSchema>;

// This internal schema is used to pass precise data to the AI for interpretation.
const InternalKundliInterpretationSchema = KundliGeneratorInputSchema.extend({
    lagna: z.string(),
    rashi: z.string(),
    nakshatra: z.string(),
    planetaryPositions: z.array(z.object({
        planet: z.string(),
        sign: z.string(),
        house: z.number(),
        degrees: z.string(),
    })),
    // We still ask the AI to determine doshas based on the rules we provide
    // as it's an interpretive task based on placements.
});


const DoshaResultSchema = z.object({
  hasDosha: z.boolean().describe("Whether the person has the dosha."),
  description: z.string().describe("A brief description of the dosha's potential impact, based on planetary positions. State 'No significant dosha found' if hasDosha is false."),
});

const HouseInfoSchema = z.object({
    house: z.number().describe("The house number (1-12)."),
    sign: z.string().describe("The zodiac sign ruling the house."),
    planets: z.array(z.string()).describe("A list of planets occupying this house. Can be empty."),
});

const DashaPeriodSchema = z.object({
    planet: z.string().describe("The planet ruling the Mahadasha."),
    startDate: z.string().describe("The start date of the Mahadasha period in YYYY-MM-DD format."),
    endDate: z.string().describe("The end date of the Mahadasha period in YYYY-MM-DD format."),
});

const KundliGeneratorOutputSchema = z.object({
  coreDetails: z.object({
    lagna: z.string().describe('The Ascendant sign (Lagna), calculated based on the rising sign at the time of birth.'),
    rashi: z.string().describe('The Moon sign (Rashi), calculated from the Moon\'s position in the zodiac.'),
    nakshatra: z.string().describe('The birth star (Nakshatra) and its Pada (quarter), calculated from the Moon\'s precise longitude.'),
  }),
  panchangDetails: z.object({
      tithi: z.string().describe("The Tithi at birth, based on the lunar day."),
      karana: z.string().describe("The Karana at birth, based on half of a Tithi."),
      yoga: z.string().describe("The Nitya Yoga at birth, based on the combined longitudes of the Sun and Moon."),
      day: z.string().describe("The day of the week of birth."),
  }),
  planetaryPositions: z.array(z.object({
      planet: z.string().describe("Name of the planet (e.g., Sun, Moon, Mars)."),
      sign: z.string().describe("The zodiac sign the planet is in."),
      house: z.number().describe("The house number the planet occupies."),
      degrees: z.string().describe("The degrees of the planet within the sign."),
  })).min(9).describe("The positions of the 9 planets (Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn, Rahu, Ketu)."),
  doshas: z.object({
      manglik: DoshaResultSchema.describe("Analysis for Manglik (Mangal) Dosha, based on Mars's placement in houses 1, 4, 7, 8, or 12."),
      kaalSarp: DoshaResultSchema.describe("Analysis for Kaal Sarp Dosha, based on whether all planets are hemmed between Rahu and Ketu."),
  }),
  bhavaChakra: z.array(HouseInfoSchema).length(12).describe("The Bhava Chakra (House Chart), showing the sign for each of the 12 houses and the planets within them."),
  navamsaChart: z.array(HouseInfoSchema).length(12).describe("The Navamsa (D9) divisional chart, crucial for marriage and later life. This is calculated by dividing each zodiac sign into 9 parts."),
  vimshottariDasha: z.array(DashaPeriodSchema).min(5).describe("A list of the major Vimshottari Dasha periods (Mahadashas), calculated from the birth Nakshatra, showing the sequence of planetary rulership."),
  basicPredictions: z.object({
      personality: z.string().describe("A brief analysis of the user's personality based on their Lagna, Rashi, and key planetary placements."),
      career: z.string().describe("A summary of potential career paths and work life based on the 10th house and its lord."),
      relationships: z.string().describe("An insight into relationship patterns and marriage based on the 7th house and Venus/Jupiter placement."),
  }),
});
export type KundliGeneratorOutput = z.infer<typeof KundliGeneratorOutputSchema>;

export async function kundliGenerator(input: KundliGeneratorInput): Promise<KundliGeneratorOutput> {
  const { db } = await connectToDatabase();
  const cacheKey = JSON.stringify(input);
  const cacheCollection = db.collection('kundli_cache');

  // 1. Check for a valid cache entry in MongoDB
  const cachedData = await cacheCollection.findOne({ _id: cacheKey });
  if (cachedData) {
    const { _id, ...kundliData } = cachedData;
    return kundliData as KundliGeneratorOutput;
  }
  
  // Step 2: Perform local, precise calculations using pre-computed data
  const planetaryData = lookupPlanetaryData(input.dateOfBirth);
  if (!planetaryData) {
      throw new Error(`Could not find planetary data for ${input.dateOfBirth}. Please use a date within the supported range.`);
  }

  const dateObj = new Date(`${input.dateOfBirth}T12:00:00Z`); // Use midday to avoid timezone issues
  const dayOfWeek = dateObj.getUTCDay();

  const tithi = getTithi(planetaryData.Sun.longitude, planetaryData.Moon.longitude);
  const nakshatra = getNakshatra(planetaryData.Moon.longitude);
  const yoga = getYoga(planetaryData.Sun.longitude, planetaryData.Moon.longitude);
  const karana = getKarana(tithi);
  const vara = getVara(dayOfWeek);

  const planetaryPositions = Object.entries(planetaryData).map(([planet, data]) => ({
      planet,
      sign: data.rashi,
      house: 1, // Placeholder: house calculation is complex
      degrees: data.longitude.toFixed(2),
  }));

  const interpretationInput: z.infer<typeof InternalKundliInterpretationSchema> = {
      ...input,
      lagna: "Aries", // Placeholder: Lagna calculation is complex
      rashi: planetaryData.Moon.rashi,
      nakshatra: `${planetaryData.Moon.nakshatra} (Pada ${planetaryData.Moon.nakshatraPada})`,
      planetaryPositions,
  };
  
  // Step 3: Call the AI flow for interpretation based on the calculated data.
  const result = await kundliGeneratorFlow(interpretationInput);

  // Step 4: We override the AI's calculation with our own precise local calculations
  // to ensure accuracy for the core details.
  const finalResult: KundliGeneratorOutput = {
    ...result,
    coreDetails: {
      ...result.coreDetails,
      rashi: planetaryData.Moon.rashi,
      nakshatra: `${planetaryData.Moon.nakshatra} (Pada ${planetaryData.Moon.nakshatraPada})`,
    },
    panchangDetails: {
      tithi: tithi.name,
      karana: karana.name,
      yoga: yoga.name,
      day: vara,
    },
    planetaryPositions: planetaryPositions,
  };

  // Step 5: Store the new result in the MongoDB cache
  await cacheCollection.updateOne(
    { _id: cacheKey },
    { $set: finalResult },
    { upsert: true }
  );

  return finalResult;
}

const prompt = ai.definePrompt({
  name: 'kundliGeneratorPrompt',
  input: {schema: InternalKundliInterpretationSchema},
  output: {schema: KundliGeneratorOutputSchema},
  prompt: `You are an expert Vedic astrologer (Jyotishi). Based *only* on the user's birth details and the pre-calculated planetary data provided, you must generate the interpretive parts of their Kundli (horoscope) report. You MUST use the Lahiri Ayanamsa for all calculations.

  User's Birth Details:
  - Name: {{{name}}}
  - Date of Birth: {{{dateOfBirth}}}
  - Time of Birth: {{{timeOfBirth}}}
  - Place of Birth: {{{placeOfBirth}}}

  Pre-calculated Core Data:
  - Lagna (Ascendant): {{{lagna}}}
  - Rashi (Moon Sign): {{{rashi}}}
  - Nakshatra: {{{nakshatra}}}
  - Planetary Positions: {{json planetaryPositions}}

  **Your Interpretive Task:**
  You must perform a full astrological analysis based *only on the data provided above*. Do not try to recalculate the core data. Your tasks are:

  1.  **Dosha Analysis**: Based on the provided planetary positions, check for major doshas:
      -   **Manglik Dosha**: Check Mars's placement in houses 1, 4, 7, 8, or 12. (You will need to determine house placements from the Lagna and planet signs).
      -   **Kaal Sarp Dosha**: Check if all planets are hemmed between Rahu and Ketu.
      Provide a 'hasDosha' boolean and a descriptive explanation for each.

  2.  **Chart Generation**: Based on the Lagna and planetary positions:
      -   **Bhava Chakra (House Chart)**: Determine the sign for each of the 12 houses and list which planets occupy each house.
      -   **Navamsa (D9) Chart**: Calculate the Navamsa divisional chart. For each of the 12 houses in the D9 chart, determine the sign and list the planets residing within it.

  3.  **Vimshottari Dasha**: Based on the provided birth Nakshatra, calculate the sequence of major Vimshottari Dasha periods (Mahadashas), providing the ruling planet and start/end dates for at least the first 5 major periods.

  4.  **Basic Predictions**: Based on the complete chart you've assembled:
      -   **Personality**: Analyze the Lagna, Rashi, and key planetary placements.
      -   **Career**: Analyze the 10th house, its lord, and relevant planets.
      -   **Relationships**: Analyze the 7th house, its lord, and Venus/Jupiter.
      
  Finally, compile all the information into the specified JSON format. The \`coreDetails\`, \`panchangDetails\`, and \`planetaryPositions\` fields will be overridden later with precise data, but you should populate them with your calculations as a reference. Every other field is your responsibility.`,
});

const kundliGeneratorFlow = ai.defineFlow(
  {
    name: 'kundliGeneratorFlow',
    inputSchema: InternalKundliInterpretationSchema,
    outputSchema: KundliGeneratorOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
