
// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI agent for predicting a user's marriage path based on their birth details.
 *
 * - marriagePathPredictor - A function that generates marriage-related predictions.
 * - MarriagePathPredictorInput - The input type for the marriagePathPredictor function.
 * - MarriagePathPredictorOutput - The return type for the marriagePathPredictor function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import { MarriagePathPredictorInputSchema, MarriagePathPredictorOutputSchema, type MarriagePathPredictorInput, type MarriagePathPrediction as MarriagePathPredictorOutput } from '@/lib/types';


export async function marriagePathPredictor(input: MarriagePathPredictorInput): Promise<MarriagePathPredictorOutput> {
  return marriagePathPredictorFlow(input);
}

const prompt = ai.definePrompt({
  name: 'marriagePathPredictorPrompt',
  input: {schema: MarriagePathPredictorInputSchema},
  output: {schema: MarriagePathPredictorOutputSchema},
  prompt: `You are a world-renowned Vedic astrologer specializing in marriage predictions. Based on the user's birth details, generate their Kundli and provide a detailed "Marriage Path" analysis. You must use the Lahiri Ayanamsa for all calculations.

  User Details:
  Name: {{{name}}}
  Date of Birth: {{{dateOfBirth}}}
  Time of Birth: {{{timeOfBirth}}}
  Place of Birth: {{{placeOfBirth}}}

  **Instructions:**
  You must first internally calculate the user's full horoscope (Lagna chart, planetary positions, Dasha periods). Then, based on your calculations, you must perform the following analysis:

  1.  **Marriage Age Prediction**: Analyze the 7th house, its lord, and the position and aspects of Venus (and Jupiter for females) to predict the likely age range for marriage. Consider any delaying planets like Saturn. Be specific (e.g., "Early marriage, likely between 22-25" or "Delayed marriage, likely after 30 due to Saturn's aspect on the 7th house").

  2.  **Partner Personality Profile**: Describe the characteristics of the likely spouse. Analyze the 7th house lord's placement, sign, and aspects, as well as planets in the 7th house, to describe their temperament, profession, and nature. For example, "With the 7th lord in a fiery sign, the partner may be energetic and ambitious."

  3.  **Ideal Marriage Periods**: Based on the calculated Vimshottari Dasha system, identify the most favorable Dasha/Antardasha (planetary periods) for marriage to occur. This is typically the period of the 7th lord, Venus, or planets associated with the 7th house. Provide 1-2 major periods in the future.

  4.  **Overall Outlook for Married Life**: Provide a summary of the married life by analyzing the strength of the 7th house, its lord, Venus, and other factors for harmony, potential challenges, and overall happiness.

  Generate a complete response in the specified JSON format. Ensure all fields are populated with insightful analysis derived directly from your astrological calculations.`,
});

const marriagePathPredictorFlow = ai.defineFlow(
  {
    name: 'marriagePathPredictorFlow',
    inputSchema: MarriagePathPredictorInputSchema,
    outputSchema: MarriagePathPredictorOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
