// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AI agent for finding auspicious marriage dates (Vivah Muhurat).
 * This flow instructs the AI to follow a detailed, rule-based algorithm and
 * now uses MongoDB for persistent caching.
 *
 * - muhuratFinder - A function that finds auspicious dates for marriage.
 * - MuhuratFinderInput - The input type for the muhuratFinder function.
 * - MuhuratFinderOutput - The return type for the muhuratFinder function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
// import { connectToDatabase } from '@/lib/mongodb';

// Define Zod schemas for input and output
const MuhuratFinderInputSchema = z.object({
  month: z.string().describe("The desired month for the wedding (e.g., 'December 2024')."),
  region: z.string().describe("The region or city for the wedding (e.g., 'North India', 'Mumbai').").optional(),
});
export type MuhuratFinderInput = z.infer<typeof MuhuratFinderInputSchema>;

const MuhuratSchema = z.object({
  date: z.string().describe("The auspicious date in YYYY-MM-DD format."),
  day: z.string().describe("The day of the week (e.g., 'Monday')."),
  tithi: z.string().describe("The Tithi on that day."),
  nakshatra: z.string().describe("The Nakshatra on that day."),
  muhuratWindow: z.string().describe("The specific auspicious time window on that day, e.g., '09:15 AM - 12:40 PM'."),
  lagna: z.string().describe("The recommended Lagna (Ascendant) during the Muhurat window."),
  notes: z.string().describe("A brief explanation of why this date is auspicious, noting favorable combinations (e.g., 'Good Tithi-Nakshatra yoga') and avoided inauspicious times (like Bhadra, Rahu Kaal etc)."),
});

const MuhuratFinderOutputSchema = z.object({
  auspiciousDates: z.array(MuhuratSchema).describe('A list of auspicious dates and their astrological details.'),
});
export type MuhuratFinderOutput = z.infer<typeof MuhuratFinderOutputSchema>;


export async function muhuratFinder(input: MuhuratFinderInput): Promise<MuhuratFinderOutput> {
  // const { db } = await connectToDatabase();
  // const cacheKey = `${input.month}-${input.region || 'default'}`;
  // const cacheCollection = db.collection('muhurat_cache');

  // // 1. Check for a valid cache entry in MongoDB
  // const cachedData = await cacheCollection.findOne({ _id: cacheKey });
  // if (cachedData) {
  //   const { _id, ...muhuratData } = cachedData;
  //   return muhuratData as MuhuratFinderOutput;
  // }

  const result = await muhuratFinderFlow(input);
  
  // Store the new result in the MongoDB cache for future requests
  // await cacheCollection.updateOne(
  //   { _id: cacheKey },
  //   { $set: result },
  //   { upsert: true }
  // );

  return result;
}


const muhuratFinderFlow = ai.defineFlow(
  {
    name: 'muhuratFinderFlow',
    inputSchema: MuhuratFinderInputSchema,
    outputSchema: MuhuratFinderOutputSchema,
  },
  async (input) => {
    
    const prompt = `You are an expert Vedic astrologer (Jyotishi) tasked with finding auspicious wedding dates (Vivah Muhurat). You MUST follow a strict, multi-step calculation process.

    **User Request:**
    - Desired Month: ${input.month}
    - Region for Timings: ${input.region || 'North India'}

    **Your Task:**
    Find up to 5 auspicious wedding dates in the month of **${input.month}**. If no dates are found in the requested month, find the next 5 available dates in the subsequent months.

    **You MUST follow this precise algorithm for each day you analyze:**

    **Step 1: Check for Inauspicious Months**
    - First, determine if the month falls into a period where marriage is forbidden.
    - **Chaturmas (July - October):** Generally inauspicious.
    - **Khar Mas (Mid-Dec to Mid-Jan, Mid-March to Mid-April):** Inauspicious.
    - **Guru/Shukra Asta (Jupiter/Venus Combustion):** Check if Jupiter or Venus are combust. If so, the month is invalid. You MUST state this if it's the reason for no dates.

    **Step 2: Filter by Auspicious Tithi (Lunar Day)**
    - If the month is valid, check the Tithi for each day. Only the following Tithis are allowed:
    - **Allowed:** Dvitiya (2), Tritiya (3), Panchami (5), Saptami (7), Dashami (10), Ekadashi (11), Trayodashi (13).
    - Discard any day that does not have one of these Tithis.

    **Step 3: Filter by Auspicious Nakshatra (Constellation)**
    - For the remaining days, check the Nakshatra. It must be one of the following:
    - **Allowed:** Rohini, Mrigashira, Magha, Uttara Phalguni, Hasta, Swati, Anuradha, Moola, Uttara Ashadha, Uttara Bhadrapada, Revati.
    - Discard any day that does not have one of these Nakshatras.

    **Step 4: Filter by Auspicious Vara (Weekday)**
    - For the remaining days, check the weekday.
    - **Allowed:** Monday, Wednesday, Thursday, Friday.
    - Discard any other day.

    **Step 5: Perform Final Checks & Find Muhurat Window**
    - For each date that has passed all the above filters, perform these final, critical checks:
    - **Bhadra Check:** Calculate if Bhadra (Vishti Karana) is present. The Muhurat time CANNOT be during Bhadra.
    - **Lagna Shuddhi:** Identify the best fixed (Sthira) or dual (Dvisvabhava) Lagna for the wedding ceremony.
    - **Avoid Rahu Kaal, etc.:** The Muhurat window MUST NOT overlap with Rahu Kaal, Gulika Kaal, or Yamaganda for the given region.
    - **Tara Bala:** The AI should make a note that "Tara Bala (matching with the couple's birth stars) should be checked with a personal astrologer." This is a mandatory sentence to include in the notes.

    **Step 6: Format the Output**
    - For each valid date that passes all checks, compile the final JSON object.
    - \`date\`, \`day\`, \`tithi\`, \`nakshatra\`: Fill these with the calculated details.
    - \`muhuratWindow\`: The calculated auspicious time window, e.g., '09:15 AM - 12:40 PM'.
    - \`lagna\`: The recommended Lagna during the Muhurat.
    - \`notes\`: Briefly justify your selection, for example: "Excellent Tithi-Nakshatra yoga. Leo Lagna is strong, and Bhadra and Rahu Kaal are avoided." And add the mandatory Tara Bala sentence.
    
    Compile the list of valid dates into the final JSON output. If no dates are found in the requested month, state this and provide the next 5 available dates.`;

    const {output} = await ai.generate({
        prompt: prompt,
        output: {
            schema: MuhuratFinderOutputSchema,
        },
    });

    if (!output) {
      throw new Error(`The Muhurat details for '${input.month}' could not be calculated. Please try again.`);
    }

    return output;
  }
);
