// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A Nakshatra Porutham (South Indian matchmaking) AI agent.
 *
 * - nakshatraPorutham - A function that handles the Nakshatra Porutham matching process.
 * - NakshatraPoruthamInput - The input type for the nakshatraPorutham function.
 * - NakshatraPoruthamResult - The return type for the nakshatraPorutham function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const BirthDetailsSchema = z.object({
  name: z.string().describe("The person's name."),
  dateOfBirth: z.string().describe("The person's date of birth in YYYY-MM-DD format."),
  timeOfBirth: z.string().describe("The person's time of birth in HH:MM format."),
  placeOfBirth: z.string().describe("The person's place of birth (e.g., city, country)."),
});

export const NakshatraPoruthamInputSchema = z.object({
    boyDetails: BirthDetailsSchema,
    girlDetails: BirthDetailsSchema,
});
export type NakshatraPoruthamInput = z.infer<typeof NakshatraPoruthamInputSchema>;

const PoruthamDetailSchema = z.object({
    name: z.string().describe("The name of the Porutham (e.g., 'Dina Porutham')."),
    isMatched: z.boolean().describe("Whether this specific Porutham is considered a match based on calculation."),
    description: z.string().describe("A brief explanation of what this Porutham represents and the reason why it matches or does not match."),
});

export const NakshatraPoruthamResultSchema = z.object({
  matchingPoints: z.number().min(0).max(10).describe("The total number of matching points out of 10, based on the number of matched poruthams."),
  poruthamDetails: z.array(PoruthamDetailSchema).length(10).describe("An array containing the results for each of the 10 main Poruthams."),
  dasaSandhi: z.object({
    hasDasaSandhi: z.boolean().describe("Whether Dasa Sandhi dosha exists, based on calculation of Vimshottari Dasha periods."),
    description: z.string().describe("A brief description of Dasa Sandhi and its potential impact if it exists."),
  }),
  overallSummary: z.string().describe("A concluding summary of the match, taking all factors into account, and providing a final recommendation."),
  recommendation: z.string().describe("A clear recommendation like 'Highly Recommended', 'Can be Considered', or 'Not Recommended', based on the final analysis."),
});
export type NakshatraPoruthamResult = z.infer<typeof NakshatraPoruthamResultSchema>;

export async function nakshatraPorutham(input: NakshatraPoruthamInput): Promise<NakshatraPoruthamResult> {
  return nakshatraPoruthamFlow(input);
}

const prompt = ai.definePrompt({
  name: 'nakshatraPoruthamPrompt',
  input: {schema: NakshatraPoruthamInputSchema},
  output: {schema: NakshatraPoruthamResultSchema},
  prompt: `You are an expert Vedic astrologer from South India, specializing in Nakshatra Porutham for marriage compatibility. You must use the Lahiri Ayanamsa for all calculations.

  Your task is to conduct a thorough compatibility analysis based on the 10-point Porutham system (Koota matching).

  Boy's Details:
  - Name: {{{boyDetails.name}}}
  - Date of Birth: {{{boyDetails.dateOfBirth}}}
  - Time of Birth: {{{boyDetails.timeOfBirth}}}
  - Place of Birth: {{{boyDetails.placeOfBirth}}}

  Girl's Details:
  - Name: {{{girlDetails.name}}}
  - Date of Birth: {{{girlDetails.dateOfBirth}}}
  - Time of Birth: {{{girlDetails.timeOfBirth}}}
  - Place of Birth: {{{girlDetails.placeOfBirth}}}

  You MUST perform the following analysis:
  
  **Step 1: Calculate Birth Nakshatras**
  - First, internally calculate the precise birth Nakshatra (and Rashi) for both the boy and the girl from their birth details.

  **Step 2: Ten Porutham Analysis**
  - For each of the following 10 Poruthams, you must determine if it matches based on the calculated Nakshatras and Rashis. For each one, explain *why* it matches or not.
    - **Dina Porutham** (Health and Prosperity): Based on Nakshatra count.
    - **Gana Porutham** (Temperament): Based on Deva, Manusha, Rakshasa Gana of Nakshatras.
    - **Mahendra Porutham** (Progeny and Longevity): Based on Nakshatra count.
    - **Stree Deergha Porutham** (Female Partner's Well-being): Based on Nakshatra count from girl to boy.
    - **Yoni Porutham** (Sexual Compatibility): Based on animal symbol of Nakshatras.
    - **Rasi Porutham** (Zodiac Harmony): Based on the relationship between the Rashis.
    - **Rasiyathipathi Porutham** (Friendship between Rashi Lords): Based on planetary friendships of the Rashi lords.
    - **Vasya Porutham** (Magnetic Attraction): Based on Rashi compatibility.
    - **Rajju Porutham** (Longevity of Husband - MOST IMPORTANT): Based on body part classification of Nakshatras. If this doesn't match, the match is generally not recommended.
    - **Vedha Porutham** (Obstacles and Afflictions): Based on pairs of conflicting Nakshatras.

  **Step 3: Calculate Matching Points**
  - Based on the number of matches from the 10 Poruthams, calculate the total score out of 10. A score of 5 or more is generally considered acceptable, but Rajju Porutham match is critical.

  **Step 4: Dasa Sandhi Analysis**
  - Internally calculate the Vimshottari Dasha periods for both individuals. Check for the presence of Dasa Sandhi, which occurs if the major planetary periods (Dasas) end or begin within one year of each other. This is a significant dosha. State whether it exists and what its impact could be.

  **Step 5: Overall Summary and Recommendation**
  - Provide a concluding summary synthesizing all the findings. Based on the score, and especially the presence/absence of major doshas like Rajju Porutham and Dasa Sandhi, provide a clear, final recommendation: 'Highly Recommended', 'Can be Considered', or 'Not Recommended'.

  Generate a complete response in the specified JSON format. Ensure all fields are populated accurately and insightfully based on your calculations.`,
});

const nakshatraPoruthamFlow = ai.defineFlow(
  {
    name: 'nakshatraPoruthamFlow',
    inputSchema: NakshatraPoruthamInputSchema,
    outputSchema: NakshatraPoruthamResultSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
