
// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI agent for generating Panchang details for a specific date.
 * This flow now uses a hybrid approach: local calculations for core elements,
 * AI for location-specific timings, and MongoDB for persistent caching.
 *
 * - panchangGenerator - A function that handles the Panchang generation process.
 * - PanchangGeneratorInput - The input type for the panchangGenerator function.
 * - PanchangResult - The return type for the panchangGenerator function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import { lookupPlanetaryData } from '@/lib/astrology-lookup';
import { getTithi, getNakshatra, getYoga, getKarana, getVara } from '@/lib/astrology-calculator';
import { connectToDatabase } from '@/lib/mongodb';


const PanchangGeneratorInputSchema = z.object({
  date: z.string().describe("The date for which to generate the panchang, in YYYY-MM-DD format."),
  location: z.string().optional().describe("The location for which to generate the panchang (e.g., 'New Delhi, India'). This is important for accuracy."),
});
export type PanchangGeneratorInput = z.infer<typeof PanchangGeneratorInputSchema>;

const PanchangGeneratorOutputSchema = z.object({
    date: z.string().describe("The date for which the panchang is generated, in YYYY-MM-DD format."),
    day: z.string().describe("The day of the week."),
    tithi: z.string().describe('The Tithi name.'),
    nakshatra: z.string().describe('The Nakshatra name.'),
    yoga: z.string().describe('The Yoga name.'),
    karana: z.string().describe('The Karana name.'),
    sunrise: z.string().describe('The sunrise time in HH:MM AM/PM format, calculated for the given location.'),
    sunset: z.string().describe('The sunset time in HH:MM AM/PM format, calculated for the given location.'),
    paksha: z.string().describe('The Paksha (lunar fortnight), either Shukla Paksha or Krishna Paksha.'),
    rahuKaal: z.string().describe('The inauspicious period of Rahu Kaal, in HH:MM AM/PM - HH:MM AM/PM format, calculated for the given location and day.'),
    gulikaKaal: z.string().describe('The period of Gulika Kaal, in HH:MM AM/PM - HH:MM AM/PM format, calculated for the given location and day.'),
    yamaganda: z.string().describe('The period of Yamaganda, in HH:MM AM/PM - HH:MM AM/PM format, calculated for the given location and day.'),
    abhijitMuhurat: z.string().describe('The auspicious Abhijit Muhurat, in HH:MM AM/PM - HH:MM AM/PM format, calculated for the given location.'),
    festival: z.string().optional().describe('Any significant Hindu festival on this day. If none, this can be omitted.'),
});
export type PanchangResult = z.infer<typeof PanchangGeneratorOutputSchema>;


export async function panchangGenerator(input: PanchangGeneratorInput): Promise<PanchangResult> {
  const { db } = await connectToDatabase();
  const cacheKey = `${input.date}-${input.location || 'default'}`;
  const cacheCollection = db.collection('panchang_cache');

  // 1. Check for a valid cache entry in MongoDB
  const cachedData = await cacheCollection.findOne({ _id: cacheKey });
  if (cachedData) {
    // Make sure to remove the MongoDB `_id` field before returning
    const { _id, ...panchangData } = cachedData;
    return panchangData as PanchangResult;
  }

  // 2. Get pre-computed planetary data if not in cache
  const planetaryData = lookupPlanetaryData(input.date);
  if (!planetaryData) {
      throw new Error(`Could not find planetary data for ${input.date}. Please use a date within the supported range.`);
  }

  // 3. Perform local, precise calculations
  const dateObj = new Date(`${input.date}T12:00:00Z`); // Use midday to avoid timezone issues
  const dayOfWeek = dateObj.getUTCDay();

  const tithi = getTithi(planetaryData.Sun.longitude, planetaryData.Moon.longitude);
  const nakshatra = getNakshatra(planetaryData.Moon.longitude);
  const yoga = getYoga(planetaryData.Sun.longitude, planetaryData.Moon.longitude);
  const karana = getKarana(tithi);
  const vara = getVara(dayOfWeek);
  
  // 4. Create a refined context for the AI with the calculated data
  const calculationContext = {
      ...input,
      tithi: tithi.name,
      paksha: tithi.paksha,
      nakshatra: nakshatra.name,
      yoga: yoga.name,
      karana: karana.name,
      day: vara,
  };
  
  // 5. Call the AI to handle location-specific timings and festival lookups
  const result = await panchangGeneratorFlow(calculationContext);

  // 6. Store the new result in the MongoDB cache for future requests
  await cacheCollection.updateOne(
    { _id: cacheKey },
    { $set: result },
    { upsert: true }
  );

  return result;
}

// Redefine input schema for the flow to include our calculated data
const InternalPanchangInputSchema = PanchangGeneratorInputSchema.extend({
    tithi: z.string(),
    paksha: z.string(),
    nakshatra: z.string(),
    yoga: z.string(),
    karana: z.string(),
    day: z.string(),
});


const prompt = ai.definePrompt({
  name: 'panchangGeneratorPrompt',
  input: {schema: InternalPanchangInputSchema},
  output: {schema: PanchangGeneratorOutputSchema},
  prompt: `You are an expert Vedic astrologer. Your task is to complete a Panchang for a given date and location, using pre-calculated core astrological data.

  **Input Data (Do NOT change these):**
  - Date: {{{date}}}
  - Day: {{{day}}}
  - Tithi: {{{tithi}}}
  - Paksha: {{{paksha}}}
  - Nakshatra: {{{nakshatra}}}
  - Yoga: {{{yoga}}}
  - Karana: {{{karana}}}

  **Your Task:**
  Based on the provided data and the location '{{{location}}}', you must calculate the remaining time-based elements and check for festivals.

  1.  **Sunrise & Sunset**: Calculate the precise sunrise and sunset times for {{{location}}} on {{{date}}}.
  2.  **Auspicious/Inauspicious Timings**: Based on the calculated sunrise/sunset and the weekday '{{{day}}}', calculate the exact time windows for:
      -   Rahu Kaal
      -   Yamaganda
      -   Gulika Kaal
      -   Abhijit Muhurat
  3.  **Festival Identification**: Based on the provided Tithi, Nakshatra, and the date, identify if any significant Hindu festival falls on this day. If not, omit the field.

  Return the complete details in the specified JSON format, ensuring that the core 'tithi', 'paksha', 'nakshatra', 'yoga', 'karana', and 'day' fields in your output EXACTLY MATCH the pre-calculated input provided above.
  `,
});

const panchangGeneratorFlow = ai.defineFlow(
  {
    name: 'panchangGeneratorFlow',
    inputSchema: InternalPanchangInputSchema,
    outputSchema: PanchangGeneratorOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);

    