// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI agent for generating Panchang details for a specific date.
 * This flow now uses the ProKerala API for accurate data and caches results in MongoDB.
 *
 * - panchangGenerator - A function that handles the Panchang generation process.
 * - PanchangGeneratorInput - The input type for the panchangGenerator function.
 * - PanchangResult - The return type for the panchangGenerator function.
 */

import { z } from 'zod';
// import { connectToDatabase } from '@/lib/mongodb';
import { fetchProkeralaPanchang } from '@/lib/prokerala-api';
import type { PanchangResult } from '@/lib/types';


const PanchangGeneratorInputSchema = z.object({
  date: z.string().describe("The date for which to generate the panchang, in YYYY-MM-DD format."),
  location: z.string().optional().describe("The location for which to generate the panchang (e.g., 'New Delhi, India'). This is important for accuracy."),
});
export type PanchangGeneratorInput = z.infer<typeof PanchangGeneratorInputSchema>;


export async function panchangGenerator(input: PanchangGeneratorInput): Promise<PanchangResult> {
  // const { db } = await connectToDatabase();
  // const cacheKey = `${input.date}-${input.location || 'default'}`;
  // const cacheCollection = db.collection('panchang_cache');

  // // 1. Check for a valid cache entry in MongoDB
  // const cachedData = await cacheCollection.findOne({ _id: cacheKey });
  // if (cachedData) {
  //   // Make sure to remove the MongoDB `_id` field before returning
  //   const { _id, ...panchangData } = cachedData;
  //   return panchangData as PanchangResult;
  // }

  // 2. Fetch data from ProKerala API if not in cache
  const apiData = await fetchProkeralaPanchang(input.date, input.location);

  // 3. Store the new result in the MongoDB cache for future requests
  // await cacheCollection.updateOne(
  //   { _id: cacheKey },
  //   { $set: apiData },
  //   { upsert: true }
  // );

  return apiData;
}
