// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI agent for handling user inquiries to a pandit.
 *
 * - panditEnquiry - A function that handles the user's enquiry process.
 * - PanditEnquiryInput - The input type for the panditEnquiry function.
 * - PanditEnquiryOutput - The return type for the panditEnquiry function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const PanditEnquiryInputSchema = z.object({
  userName: z.string().describe("The user's name."),
  userEmail: z.string().email().describe("The user's email address."),
  question: z.string().describe('The specific question the user has for the pandit.'),
  panditName: z.string().describe("The name of the pandit the user is contacting."),
});
export type PanditEnquiryInput = z.infer<typeof PanditEnquiryInputSchema>;

const PanditEnquiryOutputSchema = z.object({
  confirmationMessage: z.string().describe('A friendly and professional confirmation message to the user, assuring them their query has been received and the specified pandit will respond shortly.'),
  nextSteps: z.string().describe('A brief outline of what the user can expect next (e.g., "Expect an email response to your provided address within 24-48 hours.").'),
});
export type PanditEnquiryOutput = z.infer<typeof PanditEnquiryOutputSchema>;

export async function panditEnquiry(input: PanditEnquiryInput): Promise<PanditEnquiryOutput> {
  return panditEnquiryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'panditEnquiryPrompt',
  input: {schema: PanditEnquiryInputSchema},
  output: {schema: PanditEnquiryOutputSchema},
  prompt: `You are a helpful and professional assistant for a spiritual services website. A user is submitting an enquiry to a pandit.

  User's Name: {{{userName}}}
  User's Email: {{{userEmail}}}
  Selected Pandit: {{{panditName}}}
  Question for the Pandit:
  "{{{question}}}"

  **Your Task:**
  Generate a warm, professional, and reassuring confirmation message for the user.

  1.  **Acknowledge**: Confirm receipt of their question and mention the pandit's name they are contacting ({{{panditName}}}).
  2.  **Set Expectation**: Assure them that the pandit will personally review their query.
  3.  **Provide Next Steps**: Clearly state that the pandit will respond via email to the address provided ({{{userEmail}}}) and give an estimated timeframe (e.g., within 24-48 hours).

  **Example Structure:**
  *   \`confirmationMessage\`: "Thank you, {{{userName}}}! We have successfully forwarded your question to {{{panditName}}}. They will personally review your query and get back to you soon."
  *   \`nextSteps\`: "Please expect a response to your email address ({{{userEmail}}}) within the next 24-48 business hours. The pandit will contact you directly to discuss your question."

  Generate a suitable response in the specified JSON format.`,
});

const panditEnquiryFlow = ai.defineFlow(
  {
    name: 'panditEnquiryFlow',
    inputSchema: PanditEnquiryInputSchema,
    outputSchema: PanditEnquiryOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
