// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A puja planner AI agent.
 *
 * - pujaPlanner - A function that handles the puja planning process.
 * - PujaPlannerInput - The input type for the pujaPlanner function.
 * - PujaPlannerOutput - The return type for the pujaPlanner function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const PujaPlannerInputSchema = z.object({
  purpose: z
    .string()
    .describe("The purpose of the puja (e.g., health, career, marriage)."),
});
export type PujaPlannerInput = z.infer<typeof PujaPlannerInputSchema>;

const PujaPlannerOutputSchema = z.object({
  pujaType: z.string().describe('The recommended type of puja.'),
  idealDate: z.string().describe('The ideal date for the puja, mentioning the Tithi and/or Nakshatra.'),
  reason: z.string().describe('Reasoning for the output, explaining why the puja and date are suitable for the purpose.'),
});
export type PujaPlannerOutput = z.infer<typeof PujaPlannerOutputSchema>;

export async function pujaPlanner(input: PujaPlannerInput): Promise<PujaPlannerOutput> {
  return pujaPlannerFlow(input);
}

const prompt = ai.definePrompt({
  name: 'pujaPlannerPrompt',
  input: {schema: PujaPlannerInputSchema},
  output: {schema: PujaPlannerOutputSchema},
  prompt: `You are an expert in recommending Puja types and ideal dates based on the user's purpose, following Vedic astrological principles.

  User's Purpose: {{{purpose}}}

  **Instructions:**

  1.  **Analyze Purpose:** Understand the user's goal (e.g., success in business, health, marriage, removing obstacles).
  2.  **Recommend Puja:** Based on the purpose, recommend the most appropriate Puja. For example:
      *   Business/Career Success: Lord Ganesha Puja or Lakshmi Puja.
      *   Health: Mahamrityunjaya Jaap.
      *   Marriage: Gauri Shankar Puja.
      *   Overcoming Obstacles: Hanuman Puja.
  3.  **Find an Auspicious Date:** Find a suitable upcoming date for this Puja. This should be based on favorable Tithis (like Panchami, Ekadashi) or Nakshatras associated with the deity. Provide the date and mention the specific Tithi or Nakshatra.
  4.  **Provide Reasoning:** Clearly explain *why* you recommended this specific puja and date. Connect the deity of the puja to the user's purpose and explain why the suggested Tithi/Nakshatra is auspicious for this ritual.

  Your final output must be in the specified JSON format.`,
});

const pujaPlannerFlow = ai.defineFlow(
  {
    name: 'pujaPlannerFlow',
    inputSchema: PujaPlannerInputSchema,
    outputSchema: PujaPlannerOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
