// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI agent for finding a list of upcoming festivals.
 * This flow now uses an AI to predict upcoming festivals.
 *
 * - upcomingFestivals - A function that returns a list of the next 5 major festivals.
 * - UpcomingFestival - The type for a single upcoming festival.
 */

import { ai } from '@/ai/genkit';
import { z } from 'zod';
import { format } from 'date-fns';

const UpcomingFestivalSchema = z.object({
  name: z.string().describe("The official name of the festival."),
  date: z.string().describe("The exact date of the festival in YYYY-MM-DD format."),
  description: z.string().describe("A brief, one-sentence description of the festival's significance."),
});
export type UpcomingFestival = z.infer<typeof UpcomingFestivalSchema>;

const UpcomingFestivalsOutputSchema = z.object({
  festivals: z.array(UpcomingFestivalSchema),
});

// Main exported function for the frontend to use.
export async function upcomingFestivals(): Promise<UpcomingFestival[]> {
    const result = await upcomingFestivalsFlow();
    return result.festivals;
}

const upcomingFestivalsFlow = ai.defineFlow(
  {
    name: 'upcomingFestivalsFlow',
    outputSchema: UpcomingFestivalsOutputSchema,
  },
  async () => {
    const today = format(new Date(), 'yyyy-MM-dd');
    const prompt = `
You are an expert on Hindu festivals. List the next 5 major Hindu festivals occurring after ${today}.
Provide their name, exact date in YYYY-MM-DD format, and a brief one-sentence description.
Ensure the festivals are in chronological order.
`;

    const { output } = await ai.generate({
      prompt: prompt,
      output: {
        schema: UpcomingFestivalsOutputSchema,
      },
    });
    
    if (!output) {
        throw new Error('Could not generate upcoming festivals.');
    }
    
    return output;
  }
);
