// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI agent for finding a list of upcoming festivals.
 *
 * - upcomingFestivals - A function that returns a list of the next 5 major festivals.
 * - UpcomingFestival - The type for a single upcoming festival.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';
import { format } from 'date-fns';

const UpcomingFestivalSchema = z.object({
  name: z.string().describe("The official name of the festival."),
  date: z.string().describe("The exact date of the festival in YYYY-MM-DD format."),
  description: z.string().describe("A brief, one-sentence description of the festival's significance."),
});
export type UpcomingFestival = z.infer<typeof UpcomingFestivalSchema>;

const UpcomingFestivalsOutputSchema = z.object({
    festivals: z.array(UpcomingFestivalSchema).length(5).describe("A list of exactly 5 upcoming major Hindu festivals."),
});

// Main exported function
export async function upcomingFestivals(): Promise<UpcomingFestival[]> {
  const result = await upcomingFestivalsFlow();
  return result.festivals;
}

// The Genkit flow
const upcomingFestivalsFlow = ai.defineFlow(
  {
    name: 'upcomingFestivalsFlow',
    inputSchema: z.void(),
    outputSchema: UpcomingFestivalsOutputSchema,
  },
  async () => {
    const currentDate = format(new Date(), 'yyyy-MM-dd');
    
    const prompt = `You are an expert Vedic astrologer (Jyotishi). Your task is to identify the next 5 major Hindu festivals occurring after today's date, which is ${currentDate}.

    **Instructions:**
    1.  Consider only major, widely-celebrated festivals (e.g., Diwali, Holi, Navratri, Janmashtami, Maha Shivratri, etc.).
    2.  Provide the exact date for each festival in YYYY-MM-DD format.
    3.  For each festival, write a very brief, one-sentence description of its significance.
    4.  Return a list of exactly 5 festivals.

    Your final output must be in the specified JSON format.`;

    const { output } = await ai.generate({
        prompt,
        output: {
            schema: UpcomingFestivalsOutputSchema,
        },
    });

    if (!output) {
      throw new Error('Could not retrieve upcoming festivals at this time.');
    }
    
    return output;
  }
);
