// This is an autogenerated file from Firebase Studio.
import { config } from 'dotenv';

// Load environment variables from the .env file.
// This ensures that all server-side code, including Genkit flows and API calls,
// has access to necessary credentials like API keys.
config({ path: '.env' });
