[functions]
  schedule = "0 0 * * 0" # Runs every Sunday at midnight
  
[functions."app/api/cron/refresh-data"]
  included_files = ["src/ai/flows/**", "src/lib/**", "src/ai/genkit.ts"]

[[functions]]
  schedule = "0 0 1 * *" # Runs on the 1st of every month at midnight

[functions."app/api/cron/refresh-ephemeris"]
  included_files = ["src/lib/**"]
