// This is an autogenerated file from Firebase Studio.
'use client';

import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { featuredPandits } from '@/lib/placeholder-data';
import { notFound, useParams } from 'next/navigation';
import Image from 'next/image';
import Link from 'next/link';

import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { useToast } from '@/hooks/use-toast';
import { Loader2, MessageSquare, Send, CheckCircle, ArrowLeft } from 'lucide-react';
import { Alert, AlertTitle, AlertDescription } from '@/components/ui/alert';

const formSchema = z.object({
  name: z.string().min(2, { message: 'Please enter your name.' }),
  email: z.string().email({ message: 'Please enter a valid email address.' }),
  question: z.string().min(20, {
    message: 'Please describe your question in at least 20 characters.',
  }),
});

export default function PanditConsultPage() {
  const [enquiryResult, setEnquiryResult] = useState<any | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();
  const params = useParams();
  const panditId = params.id as string;

  const pandit = featuredPandits.find((p) => p.id === panditId);

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      name: '',
      email: '',
      question: '',
    },
  });

  if (!pandit) {
    notFound();
  }

  async function onSubmit(values: z.infer<typeof formSchema>) {
    setIsLoading(true);
    setEnquiryResult(null);
    try {
        // AI flow is removed, showing a generic success message.
      setEnquiryResult({
          confirmationMessage: `Thank you, ${values.name}! Your question has been sent to ${pandit.name}.`,
          nextSteps: `Please expect a response to your email address (${values.email}) within 24-48 hours.`
      });
      form.reset();
    } catch (error) {
      console.error('Error submitting enquiry:', error);
      toast({
        variant: 'destructive',
        title: 'An error occurred',
        description: 'Failed to submit your enquiry. Please try again.',
      });
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <div className="container mx-auto px-4 md:px-6 py-12 md:py-20">
      <div className="max-w-4xl mx-auto">
        
        <div className="mb-8">
            <Button asChild variant="outline">
                <Link href={`/pandits/${panditId}`}>
                    <ArrowLeft className="mr-2 h-4 w-4" />
                    Back to Profile
                </Link>
            </Button>
        </div>

        <div className="text-center mb-12">
          <MessageSquare className="h-12 w-12 mx-auto text-primary mb-4" />
          <h1 className="text-4xl md:text-5xl font-headline font-bold">
            Consult with {pandit.name}
          </h1>
          <p className="mt-4 text-lg text-muted-foreground">
            Fill out the form below to send your question directly to {pandit.name}.
          </p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="md:col-span-1">
                <Card>
                    <CardContent className="p-4 text-center">
                        <Image 
                            src={pandit.imageUrl}
                            alt={pandit.name}
                            width={200}
                            height={200}
                            className="rounded-full object-cover w-32 h-32 mx-auto shadow-lg mb-4"
                            data-ai-hint="portrait priest"
                        />
                        <h2 className="text-xl font-headline font-bold">{pandit.name}</h2>
                        <p className="text-muted-foreground">{pandit.location}</p>
                    </CardContent>
                </Card>
            </div>

            <div className="md:col-span-2">
                {enquiryResult ? (
                    <Alert variant="default" className="bg-green-100/50 border-green-300">
                        <CheckCircle className="h-5 w-5 text-green-600" />
                        <AlertTitle className="font-headline text-xl text-green-900">{enquiryResult.confirmationMessage}</AlertTitle>
                        <AlertDescription className="text-green-800">
                            {enquiryResult.nextSteps}
                        </AlertDescription>
                    </Alert>
                ) : (
                <Card>
                    <CardHeader>
                        <CardTitle>Your Details</CardTitle>
                        <CardDescription>This information will be sent to the pandit to initiate the consultation.</CardDescription>
                    </CardHeader>
                    <CardContent>
                    <Form {...form}>
                        <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
                        <FormField
                            control={form.control}
                            name="name"
                            render={({ field }) => (
                            <FormItem>
                                <FormLabel>Your Name</FormLabel>
                                <FormControl>
                                <Input placeholder="Enter your full name" {...field} />
                                </FormControl>
                                <FormMessage />
                            </FormItem>
                            )}
                        />
                        <FormField
                            control={form.control}
                            name="email"
                            render={({ field }) => (
                            <FormItem>
                                <FormLabel>Your Email</FormLabel>
                                <FormControl>
                                <Input placeholder="you@example.com" {...field} />
                                </FormControl>
                                <FormDescription>The pandit will respond to this email address.</FormDescription>
                                <FormMessage />
                            </FormItem>
                            )}
                        />
                        <FormField
                            control={form.control}
                            name="question"
                            render={({ field }) => (
                            <FormItem>
                                <FormLabel>Your Question</FormLabel>
                                <FormControl>
                                <Textarea
                                    placeholder="Please describe your situation and your question in detail. For example: 'We are considering marriage. My details are..., my partner's details are... Could you analyze our match and suggest auspicious dates?'"
                                    className="min-h-[150px]"
                                    {...field}
                                />
                                </FormControl>
                                <FormMessage />
                            </FormItem>
                            )}
                        />

                        <Button type="submit" disabled={isLoading} className="w-full" size="lg">
                            {isLoading ? (
                            <>
                                <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                                Submitting...
                            </>
                            ) : (
                            <>
                                <Send className="mr-2 h-5 w-5" />
                                Submit Enquiry
                            </>
                            )}
                        </Button>
                        </form>
                    </Form>
                    </CardContent>
                </Card>
                )}
            </div>
        </div>
        
      </div>
    </div>
  );
}
