// This is an autogenerated file from Firebase Studio.
import { NextResponse } from 'next/server';
import { upcomingFestivals } from '@/ai/flows/upcoming-festivals';
import { panchangGenerator } from '@/ai/flows/panchang-generator';
import { format } from 'date-fns';

export const dynamic = 'force-dynamic'; // an API route that is not cached

/**
 * This endpoint is designed to be called periodically by a cron job or scheduler.
 * It refreshes and caches data that is frequently accessed but changes infrequently,
 * such as the list of upcoming festivals and today's panchang.
 */
export async function GET() {
  const results: { [key: string]: { success: boolean; message: string; data?: any } } = {};
  
  try {
    // 1. Refresh and cache upcoming festivals
    const festivals = await upcomingFestivals();
    results['upcoming_festivals'] = {
        success: true,
        message: 'Successfully refreshed and cached upcoming festivals.',
        data: { count: festivals.length }
    };
  } catch (error: any) {
    results['upcoming_festivals'] = {
        success: false,
        message: `Failed to refresh upcoming festivals: ${error.message}`
    };
  }

  try {
    // 2. Refresh and cache today's panchang
    const today = format(new Date(), 'yyyy-MM-dd');
    await panchangGenerator({ date: today });
     results['todays_panchang'] = {
        success: true,
        message: 'Successfully refreshed and cached panchang for today.'
    };
  } catch (error: any)
  {
     results['todays_panchang'] = {
        success: false,
        message: `Failed to refresh today's panchang: ${error.message}`
    };
  }

  const allSucceeded = Object.values(results).every(r => r.success);

  return NextResponse.json(
    { 
        success: allSucceeded,
        message: allSucceeded ? 'All data refreshed successfully.' : 'One or more tasks failed.',
        results 
    },
    { status: allSucceeded ? 200 : 500 }
  );
}
