// This is an autogenerated file from Firebase Studio.
import { NextResponse } from 'next/server';
import { connectToDatabase } from '@/lib/mongodb';

export async function GET() {
  try {
    const { client, db } = await connectToDatabase();
    // Optional: Ping the database to confirm a successful connection
    await db.command({ ping: 1 });
    return NextResponse.json({ success: true, message: "Successfully connected to MongoDB." });
  } catch (error: any) {
    console.error('MongoDB connection test endpoint error:', error);
    return NextResponse.json(
      { success: false, error: error.message },
      { status: 500 }
    );
  }
}
