// This is an autogenerated file from Firebase Studio.
import { config } from 'dotenv';
config({ path: '.env' });

import '@/ai/flows/puja-planner.ts';
import '@/ai/flows/kundli-generator.ts';
import '@/ai/flows/panchang-generator.ts';
import '@/ai/flows/pandit-enquiry.ts';
import '@/ai/flows/festival-finder.ts';
import '@/ai/flows/upcoming-festivals.ts';
