
// This is an autogenerated file from Firebase Studio.
'use client';

import { useState, useEffect, Suspense } from 'react';
import { useSearchParams } from 'next/navigation';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useToast } from '@/hooks/use-toast';
import { festivalFinder } from '@/ai/flows/festival-finder';
import type { FestivalDetails } from '@/lib/types';
import { format, parse } from 'date-fns';

import { Form, FormControl, FormField, FormItem, FormMessage } from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Loader2, Search, Info, BookOpen, CalendarHeart, Sun, Star, BrainCircuit, Clock, HelpCircle, CheckCircle, Ban } from 'lucide-react';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Separator } from '@/components/ui/separator';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';


const formSchema = z.object({
  query: z.string().min(3, {
    message: 'Please enter a valid festival query (e.g., Diwali 2024).',
  }),
});

function FestivalSearchComponent() {
  const searchParams = useSearchParams();
  const queryParam = searchParams.get('query');

  const [festivalDetails, setFestivalDetails] = useState<FestivalDetails | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      query: queryParam || '',
    },
  });
  
  const handleSearch = async (query: string) => {
    if (!query) return;
    setIsLoading(true);
    setFestivalDetails(null);
    try {
      const result = await festivalFinder({ query });
      setFestivalDetails(result);
    } catch (error: any) {
      console.error('Error finding festival:', error);
      toast({
        variant: 'destructive',
        title: 'An error occurred',
        description: error.message || 'Failed to find festival details. The AI may be busy or could not find information for that query.',
      });
    } finally {
      setIsLoading(false);
    }
  }

  useEffect(() => {
    if (queryParam) {
        form.setValue('query', queryParam);
        handleSearch(queryParam);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [queryParam]);


  async function onSubmit(values: z.infer<typeof formSchema>) {
    await handleSearch(values.query);
  }
  
  const isMultiDay = festivalDetails && festivalDetails.dailyDetails.length > 1;

  return (
    <div className="space-y-8">
      <Card>
        <CardHeader>
          <CardTitle className="font-headline text-3xl">Find a Festival</CardTitle>
          <CardDescription>
            Search for any Hindu festival (e.g., "Raksha Bandhan 2025", "Holi") to get AI-generated details.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="flex items-start space-x-2">
              <FormField
                control={form.control}
                name="query"
                render={({ field }) => (
                  <FormItem className="flex-grow">
                    <FormControl>
                      <Input placeholder="e.g., Raksha Bandhan 2025" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <Button type="submit" disabled={isLoading} size="lg">
                {isLoading ? (
                  <Loader2 className="h-5 w-5 animate-spin" />
                ) : (
                  <Search className="h-5 w-5" />
                )}
                <span className="sr-only">Search</span>
              </Button>
            </form>
          </Form>
        </CardContent>
      </Card>
      
      {isLoading && (
            <div className="flex flex-col items-center justify-center h-48">
              <Loader2 className="h-8 w-8 animate-spin text-primary" />
              <p className="mt-4 text-muted-foreground">Searching for festival details...</p>
            </div>
      )}

      {festivalDetails && (
        <Card className="mt-6 animate-in fade-in-50 duration-500 bg-primary/5 border-primary/20">
          <CardHeader className="text-center">
            <CalendarHeart className="h-10 w-10 mx-auto text-primary mb-2"/>
            <CardTitle className="font-headline text-3xl">{festivalDetails.festivalName}</CardTitle>
            <CardDescription className="text-lg max-w-2xl mx-auto">
              {festivalDetails.mainDescription}
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">

          {isMultiDay ? (
            <Accordion type="single" collapsible className="w-full space-y-4" defaultValue="item-0">
                {festivalDetails.dailyDetails.map((dayDetail, index) => (
                    <AccordionItem value={`item-${index}`} key={index} className="border-b-0">
                      <Card className="shadow-sm">
                        <AccordionTrigger className="p-6 font-headline text-xl text-left">
                          {dayDetail.dayName} - {format(parse(dayDetail.date, 'yyyy-MM-dd', new Date()), 'MMMM d, yyyy')}
                        </AccordionTrigger>
                        <AccordionContent className="px-6 pb-6">
                            <FestivalDayDetails details={dayDetail} />
                        </AccordionContent>
                      </Card>
                    </AccordionItem>
                ))}
            </Accordion>
          ) : (
             festivalDetails.dailyDetails[0] && <FestivalDayDetails details={festivalDetails.dailyDetails[0]} />
          )}
            
            <Card>
                <CardHeader>
                    <CardTitle className="font-headline text-xl flex items-center gap-2">
                        <BrainCircuit className="h-6 w-6 text-primary flex-shrink-0" />
                        Traditional Calculation Method
                    </CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                    {festivalDetails.calculationMethod.split('\n').map((step, index) => {
                       const stepText = step.replace(/^\d+\.\s*/, '');
                       return (
                           <div key={index} className="flex items-start gap-3">
                                <div className="flex-shrink-0 bg-primary/20 text-primary font-bold rounded-full h-6 w-6 flex items-center justify-center text-sm">{index + 1}</div>
                                <p className="text-muted-foreground">{stepText}</p>
                           </div>
                       )
                    })}
                </CardContent>
            </Card>

          </CardContent>
        </Card>
      )}
    </div>
  );
}

const FestivalDayDetails = ({ details }: { details: FestivalDetails['dailyDetails'][0] }) => (
  <div className="space-y-6">
    <Alert>
      <Info className="h-5 w-5" />
      <AlertTitle className="font-headline text-lg">Detailed Summary</AlertTitle>
      <AlertDescription>
        {details.summary}
      </AlertDescription>
    </Alert>
    
    <Card>
      <CardHeader className="pb-2">
          <CardTitle className="text-lg font-semibold flex items-center gap-2 text-green-700"><CheckCircle />Tithi Timings</CardTitle>
      </CardHeader>
      <CardContent className="space-y-2">
          <TimingRow label="Tithi" value={`${details.tithi}`} />
          <TimingRow label="Begins" value={format(parse(details.tithiBegins, 'yyyy-MM-dd HH:mm', new Date()), 'MMM d, h:mm a')} />
          <TimingRow label="Ends" value={format(parse(details.tithiEnds, 'yyyy-MM-dd HH:mm', new Date()), 'MMM d, h:mm a')} />
      </CardContent>
    </Card>

    <InfoCard icon={<Star className="h-6 w-6 text-primary" />} title="Nakshatra" value={details.nakshatra} />
    
    <Separator />
    
    <div>
      <h3 className="text-center font-headline text-xl mb-4">Auspicious & Inauspicious Timings</h3>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Card>
              <CardHeader className="pb-2">
                  <CardTitle className="text-lg font-semibold flex items-center gap-2 text-green-700"><CheckCircle />Auspicious</CardTitle>
              </CardHeader>
              <CardContent className="space-y-2">
                  <TimingRow label="Abhijit Muhurat" value={details.abhijitMuhurat} />
                  <TimingRow label="Gulika Kaal" value={details.gulikaKaal} />
              </CardContent>
          </Card>
          <Card>
              <CardHeader className="pb-2">
                  <CardTitle className="text-lg font-semibold flex items-center gap-2 text-destructive"><Ban />Inauspicious</CardTitle>
              </CardHeader>
              <CardContent className="space-y-2">
                  <TimingRow label="Rahu Kaal" value={details.rahuKaal} />
                  <TimingRow label="Yamaganda" value={details.yamaganda} />
              </CardContent>
          </Card>
      </div>
    </div>

    <Separator />

    <InfoBlock icon={<BookOpen className="h-6 w-6 text-primary flex-shrink-0" />} title="Rituals & Customs" content={details.rituals} />
  </div>
);


function TimingRow({ label, value }: { label: string, value: string }) {
    return (
        <div className="flex justify-between items-center text-sm border-b pb-1 last:border-b-0">
            <span className="text-muted-foreground">{label}</span>
            <span className="font-mono font-semibold">{value}</span>
        </div>
    )
}

function InfoCard({ icon, title, value }: { icon: React.ReactNode, title: string, value: string }) {
  return (
    <Card className="p-4 flex items-center gap-4">
      {icon}
      <div>
        <p className="text-sm text-muted-foreground">{title}</p>
        <p className="font-bold text-lg">{value}</p>
      </div>
    </Card>
  );
}

function InfoBlock({ icon, title, content }: { icon: React.ReactNode, title: string, content: string }) {
    return (
        <Card className="p-6">
           <div className="flex items-start">
             {icon}
             <div className="ml-4">
                <h3 className="font-headline text-xl mb-2">{title}</h3>
                <p className="text-muted-foreground whitespace-pre-wrap">{content}</p>
             </div>
           </div>
        </Card>
    )
}

export function FestivalSearch() {
  return (
    <Suspense fallback={<div>Loading...</div>}>
      <FestivalSearchComponent />
    </Suspense>
  )
}
