// This is an autogenerated file from Firebase Studio.
import { NextResponse } from 'next/server';
import { connectToDatabase } from '@/lib/mongodb';
import { fetchProkeralaPanchang } from '@/lib/prokerala-api';
import { format, subDays } from 'date-fns';
import { config } from 'dotenv';

config(); // Load environment variables from .env file

export const dynamic = 'force-dynamic';

/**
 * Fetches raw planetary position data for a given date by using the advanced
 * panchang endpoint and extracting the detailed planetary information.
 * @param dateString The date to fetch data for (YYYY-MM-DD).
 * @param location The location for the calculation.
 * @returns The fetched planetary data.
 */
async function fetchAndCachePlanetaryData(dateString: string, location: string) {
    // We use the advanced panchang endpoint, which contains nakshatra and rashi
    // information for each planet, serving as our source for ephemeris data.
    const panchangData = await fetchProkeralaPanchang(dateString, location);
    
    // In a real app with a dedicated planet positions API, you would map those fields here.
    // For now, we are saving the entire detailed panchang object as it contains the necessary info.
    const planetaryData = panchangData; 

    const { db } = await connectToDatabase();
    const collection = db.collection('ephemeris_cache');

    await collection.updateOne(
        { _id: dateString },
        { $set: { date: dateString, data: planetaryData } }, // Store raw planetary data
        { upsert: true }
    );
    return planetaryData;
}


/**
 * This endpoint is designed to be called monthly by a cron job.
 * Its purpose is to pre-populate and keep the local ephemeris data (planetary positions)
 * in MongoDB up-to-date by fetching it from the Prokerala API.
 * This reduces on-demand API calls for Kundli generation.
 */
export async function GET() {
    console.log('Starting monthly ephemeris data refresh job...');

    // For this prototype, we will fetch and update data for the past 3 days
    // to demonstrate the concept without using excessive API quota.
    const results: { [key: string]: { success: boolean; message: string; error?: string } } = {};
    
    for (let i = 0; i < 3; i++) {
        const dateToFetch = subDays(new Date(), i);
        const dateString = format(dateToFetch, 'yyyy-MM-dd');
        
        try {
            await fetchAndCachePlanetaryData(dateString, 'New Delhi, India');
            results[dateString] = {
                success: true,
                message: `Successfully fetched and cached ephemeris data for ${dateString}.`
            };
        } catch (error: any) {
             results[dateString] = {
                success: false,
                message: `Failed to refresh ephemeris for ${dateString}.`,
                error: error.message || 'Unknown error',
            };
            console.error(`Ephemeris refresh error for ${dateString}:`, error);
        }
    }
    
    const allSucceeded = Object.values(results).every(r => r.success);

    return NextResponse.json(
        { 
            success: allSucceeded,
            message: allSucceeded ? 'Ephemeris data refresh completed successfully.' : 'One or more ephemeris refresh tasks failed.',
            results 
        },
        { status: allSucceeded ? 200 : 500 }
    );
}
