// This is an autogenerated file from Firebase Studio.
import { NextResponse } from 'next/server';
import { connectToDatabase } from '@/lib/mongodb';
import { ai } from '@/ai/genkit';
import { z } from 'zod';
import { format, subDays } from 'date-fns';
import { config } from 'dotenv';

config(); // Load environment variables from .env file

export const dynamic = 'force-dynamic';

const PlanetaryDataSchema = z.object({
    rashi: z.string(),
    nakshatra: z.string(),
    nakshatraPada: z.number(),
    longitude: z.number(),
});

const DailyEphemerisSchema = z.object({
    Sun: PlanetaryDataSchema,
    Moon: PlanetaryDataSchema,
    Mars: PlanetaryDataSchema,
    Mercury: PlanetaryDataSchema,
    Jupiter: PlanetaryDataSchema,
    Venus: PlanetaryDataSchema,
    Saturn: PlanetaryDataSchema,
    Rahu: PlanetaryDataSchema,
});


/**
 * Fetches raw planetary position data for a given date by using an AI model
 * to generate plausible ephemeris data.
 * @param dateString The date to fetch data for (YYYY-MM-DD).
 * @returns The fetched planetary data.
 */
async function fetchAndCachePlanetaryData(dateString: string) {
    const prompt = `Generate the planetary ephemeris data (Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn, Rahu) for the date: ${dateString}. Use the Lahiri Ayanamsa. Provide the rashi, nakshatra, nakshatra pada, and longitude for each planet.`;

    const { output } = await ai.generate({
        prompt,
        output: {
            schema: DailyEphemerisSchema
        }
    });

    if (!output) {
        throw new Error(`AI failed to generate ephemeris data for ${dateString}`);
    }

    const { db } = await connectToDatabase();
    const collection = db.collection('ephemeris_cache');

    await collection.updateOne(
        { _id: dateString },
        { $set: { date: dateString, data: output } }, // Store raw planetary data
        { upsert: true }
    );
    return output;
}


/**
 * This endpoint is designed to be called monthly by a cron job.
 * Its purpose is to pre-populate and keep the local ephemeris data (planetary positions)
 * in MongoDB up-to-date by fetching it from an AI model.
 * This reduces on-demand API calls for Kundli generation.
 */
export async function GET() {
    console.log('Starting monthly ephemeris data refresh job...');

    // For this prototype, we will fetch and update data for the past 3 days
    // to demonstrate the concept.
    const results: { [key: string]: { success: boolean; message: string; error?: string } } = {};
    
    for (let i = 0; i < 3; i++) {
        const dateToFetch = subDays(new Date(), i);
        const dateString = format(dateToFetch, 'yyyy-MM-dd');
        
        try {
            await fetchAndCachePlanetaryData(dateString);
            results[dateString] = {
                success: true,
                message: `Successfully fetched and cached ephemeris data for ${dateString}.`
            };
        } catch (error: any) {
             results[dateString] = {
                success: false,
                message: `Failed to refresh ephemeris for ${dateString}.`,
                error: error.message || 'Unknown error',
            };
            console.error(`Ephemeris refresh error for ${dateString}:`, error);
        }
    }
    
    const allSucceeded = Object.values(results).every(r => r.success);

    return NextResponse.json(
        { 
            success: allSucceeded,
            message: allSucceeded ? 'Ephemeris data refresh completed successfully.' : 'One or more ephemeris refresh tasks failed.',
            results 
        },
        { status: allSucceeded ? 200 : 500 }
    );
}
