// This is an autogenerated file from Firebase Studio.
import { NextResponse } from 'next/server';
import { fetchProkeralaPanchang } from '@/lib/prokerala-api';
import { format } from 'date-fns';

export async function GET() {
  try {
    const today = format(new Date(), 'yyyy-MM-dd');
    const location = 'New Delhi, India';
    const panchangData = await fetchProkeralaPanchang(today, location);
    return NextResponse.json({ success: true, data: panchangData });
  } catch (error: any) {
    console.error('Prokerala test endpoint error:', error);
    return NextResponse.json(
      { success: false, error: error.message },
      { status: 500 }
    );
  }
}
